const TW=window.TW; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function requireAdmin(){const s=TW.session();if(!s||s.user.role!=='admin')location.href='/admin/login.html';return s}
function ticketRows(tickets){return tickets.map(t=>`<tr><td>${TW.escapeHtml(t.ticketId)}</td><td>${TW.escapeHtml(t.label)}</td><td>${TW.escapeHtml(t.section)}</td><td>${TW.escapeHtml(t.row)}</td><td>${TW.escapeHtml(t.seat)}</td><td>${TW.money(t.price,t.currency)}</td><td><span class="badge ${t.status==='available'?'green':'red'}">${t.status}</span></td><td><button class="btn ghost" data-edit-ticket="${t.ticketId}">Edit</button> <button class="btn danger" data-del-ticket="${t.ticketId}">Delete</button></td></tr>`).join('')}
async function stats(){const {stats}=await TW.api('/admin/stats');['users','events','orders','soldTickets'].forEach(k=>{const el=document.querySelector('[data-stat="'+k+'"]');if(el)el.textContent=stats[k]})}
async function users(){const el=$('#usersTable');if(!el)return;const {users}=await TW.api('/admin/users');el.innerHTML=users.map(u=>`<tr><td>${TW.escapeHtml(u.name)}</td><td>${TW.escapeHtml(u.email)}</td><td>${u.role}</td><td><span class="badge ${u.suspended?'red':'green'}">${u.suspended?'Suspended':'Active'}</span></td><td><button class="btn ghost" data-suspend="${u._id}" data-value="${!u.suspended}">${u.suspended?'Unsuspend':'Suspend'}</button> <button class="btn danger" data-delete-user="${u._id}">Delete</button></td></tr>`).join('');$$('[data-suspend]').forEach(b=>b.onclick=async()=>{await TW.api('/admin/users/'+b.dataset.suspend+'/suspend',{method:'PATCH',body:JSON.stringify({suspended:b.dataset.value==='true'})});users();stats()});$$('[data-delete-user]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this user permanently?')){await TW.api('/admin/users/'+b.dataset.deleteUser,{method:'DELETE'});users();stats()}})}
async function events(){const el=$('#eventsTable');if(!el)return;const {events}=await TW.api('/events/all');el.innerHTML=events.map(e=>`<tr><td>${TW.escapeHtml(e.title)}</td><td>${TW.escapeHtml(e.date)}</td><td>${TW.escapeHtml(e.venue)}</td><td>${e.tickets.length}</td><td><a class="btn ghost" href="/admin/edit-event.html?id=${e._id}">Edit</a> <button class="btn danger" data-delete-event="${e._id}">Delete</button></td></tr>`).join('');$$('[data-delete-event]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this event and its tickets?')){await TW.api('/events/'+b.dataset.deleteEvent,{method:'DELETE'});events();stats()}})}
async function orders(){const el=$('#ordersTable');if(!el)return;const {orders}=await TW.api('/orders');el.innerHTML=orders.map(o=>`<tr><td>${o.orderNumber}</td><td>${TW.escapeHtml(o.user?.email||'')}</td><td>${TW.escapeHtml(o.event?.title||'')}</td><td>${TW.money(o.total,o.currency)}</td><td>${o.status}</td><td>${new Date(o.createdAt).toLocaleString()}</td></tr>`).join('')}
async function tickets(){const el=$('#ticketsTable');if(!el)return;const {tickets}=await TW.api('/admin/tickets');el.innerHTML=tickets.map(t=>`<tr><td>${TW.escapeHtml(t.eventTitle)}</td><td>${TW.escapeHtml(t.label)}</td><td>${TW.escapeHtml(t.section)}</td><td>${TW.escapeHtml(t.row)}</td><td>${TW.escapeHtml(t.seat)}</td><td>${TW.money(t.price,t.currency)}</td><td>${t.status}</td><td><a class="btn ghost" href="/admin/edit-ticket.html?eventId=${t.eventId}&ticketId=${t.ticketId}">Edit</a></td></tr>`).join('')}
function eventForm(){const f=$('#eventForm');if(!f)return;const id=new URLSearchParams(location.search).get('id');(async()=>{if(id){const {event:e}=await TW.api('/events/'+id);for(const [k,v] of Object.entries(e)){if(f.elements[k])f.elements[k].value=Array.isArray(v)?JSON.stringify(v):v}f.dataset.id=id}})();f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));data.sections=JSON.parse(data.sections||'[]');data.tickets=JSON.parse(data.tickets||'[]');try{const path=f.dataset.id?'/events/'+f.dataset.id:'/events';await TW.api(path,{method:f.dataset.id?'PUT':'POST',body:JSON.stringify(data)});location.href='/admin/events.html'}catch(err){alert(err.message)}}}
function giveawayForm(){const f=$('#giveawayForm');if(!f)return;const id=new URLSearchParams(location.search).get('id');(async()=>{if(id){const {giveaways}=await TW.api('/giveaways/all');const g=giveaways.find(x=>x._id===id);if(g)for(const [k,v] of Object.entries(g)){if(f.elements[k])f.elements[k].value=v}}})();f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));data.entries=Number(data.entries||0);const path=id?'/giveaways/'+id:'/giveaways';await TW.api(path,{method:id?'PUT':'POST',body:JSON.stringify(data)});location.href='/admin/giveaways.html'}}
async function giveaways(){const el=$('#giveawaysTable');if(!el)return;const {giveaways}=await TW.api('/giveaways/all');el.innerHTML=giveaways.map(g=>`<tr><td>${TW.escapeHtml(g.title)}</td><td>${TW.escapeHtml(g.prize)}</td><td>${g.status}</td><td>${g.entries}</td><td><a class="btn ghost" href="/admin/edit-giveaway.html?id=${g._id}">Edit</a> <button class="btn danger" data-del-g="${g._id}">Delete</button></td></tr>`).join('');$$('[data-del-g]').forEach(b=>b.onclick=async()=>{if(confirm('Delete giveaway?')){await TW.api('/giveaways/'+b.dataset.delG,{method:'DELETE'});giveaways()}})}
async function boot(){if(location.pathname==='/admin/login.html'){const f=$('#adminLogin');if(f)f.onsubmit=async e=>{e.preventDefault();try{const d=await TW.api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});if(d.user.role!=='admin')throw new Error('Admin account required');localStorage.setItem('tw_session',JSON.stringify(d));location.href='/admin/index.html'}catch(err){$('#msg').textContent=err.message}};return}requireAdmin();stats();users();events();orders();tickets();eventForm();giveawayForm();giveaways();}
document.addEventListener('DOMContentLoaded',boot);
