const API=window.location.origin+'/api';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const session=()=>JSON.parse(localStorage.getItem('tw_session')||'null');
async function api(path,opts={}){const s=session();const headers={'Content-Type':'application/json',...(opts.headers||{})};if(s?.token)headers.Authorization='Bearer '+s.token;const r=await fetch(API+path,{...opts,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Request failed');return d}
function setSession(d){localStorage.setItem('tw_session',JSON.stringify(d));} function logout(){localStorage.removeItem('tw_session');location.href='/';}
function nav(){const n=$('#navlinks');if(!n)return;const s=session();n.innerHTML=s?`<a href="/events.html">Events</a><a href="/my-tickets.html">My Tickets</a><a href="/profile.html">Profile</a>${s.user.role==='admin'?'<a href="/admin/index.html">Admin</a>':''}<a href="#" id="logout">Logout</a>`:`<a href="/events.html">Events</a><a href="/login.html">Login</a><a class="btn" href="/register.html">Create account</a>`;$('#logout')?.addEventListener('click',e=>{e.preventDefault();logout()})}
function money(n,c='USD'){return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(n||0))}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function loadEvents(target='#eventGrid',q=''){const el=$(target);if(!el)return;try{const {events}=await api('/events'+(q?`?q=${encodeURIComponent(q)}`:''));el.innerHTML=events.length?events.map(e=>`<a class="card" href="/event-details.html?id=${e._id}"><img class="event-img" src="${escapeHtml(e.imageUrl||'https://placehold.co/800x450?text=TicketWAVES')}" alt=""><div class="card-body"><div class="eyebrow">${escapeHtml(e.artist||e.category)}</div><h3>${escapeHtml(e.title)}</h3><div class="muted">${escapeHtml(e.date)} · ${escapeHtml(e.time)}</div><div class="muted">${escapeHtml(e.venue)}, ${escapeHtml(e.city)}</div></div></a>`).join(''):'<div class="empty">No events found.</div>'}catch(e){el.innerHTML=`<div class="alert">${escapeHtml(e.message)}</div>`}}
async function loadGiveaways(){const el=$('#giveawayGrid');if(!el)return;try{const {giveaways}=await api('/giveaways');el.innerHTML=giveaways.length?giveaways.map(g=>`<div class="card"><img class="event-img" src="${escapeHtml(g.imageUrl||'https://placehold.co/800x450?text=Giveaway')}" alt=""><div class="card-body"><div class="eyebrow">Giveaway</div><h3>${escapeHtml(g.title)}</h3><p>${escapeHtml(g.description)}</p><strong>${escapeHtml(g.prize)}</strong><button class="btn" data-enter="${g._id}" style="width:100%;margin-top:12px">Enter giveaway</button></div></div>`).join(''):'<div class="empty">No giveaways right now.</div>';$$('[data-enter]').forEach(b=>b.onclick=async()=>{if(!session())return location.href='/login.html';try{await api('/giveaways/'+b.dataset.enter+'/enter',{method:'POST'});b.textContent='Entry received';b.disabled=true}catch(e){alert(e.message)}})}catch(e){el.innerHTML=`<div class="alert">${escapeHtml(e.message)}</div>`}}
async function initEventDetails(){if(!$('#eventTitle'))return;const id=new URLSearchParams(location.search).get('id');if(!id)return;try{const {event:e}=await api('/events/'+id);$('#eventTitle').textContent=e.title;$('#eventArtist').textContent=e.artist||e.category;$('#eventMeta').textContent=`${e.date} · ${e.time} · ${e.venue}, ${e.city}`;$('#eventImage').src=e.imageUrl||'https://placehold.co/1000x560?text=TicketWAVES';$('#eventDescription').textContent=e.description||'Tickets available now.';const available=e.tickets.filter(t=>t.status==='available');$('#ticketList').innerHTML=available.length?available.map(t=>`<label class="ticket row"><input type="checkbox" value="${t.ticketId}" data-price="${t.price}"><div class="ticket-main"><strong>${escapeHtml(t.label)}</strong><span class="muted">Section ${escapeHtml(t.section||'-')} · Row ${escapeHtml(t.row||'-')} · Seat ${escapeHtml(t.seat||'-')}</span></div><strong style="margin-left:auto">${money(t.price,t.currency)}</strong></label>`).join(''):'<div class="empty">Sold out.</div>';$$('#ticketList input').forEach(x=>x.onchange=()=>{const total=$$('#ticketList input:checked').reduce((s,i)=>s+Number(i.dataset.price),0);$('#selectionTotal').textContent=money(total)});$('#buyBtn').onclick=async()=>{if(!session())return location.href='/login.html?next='+encodeURIComponent(location.href);const ids=$$('#ticketList input:checked').map(x=>x.value);if(!ids.length)return alert('Select a ticket first');location.href='/checkout.html?eventId='+encodeURIComponent(id)+'&ticketIds='+encodeURIComponent(ids.join(','))};}catch(e){$('#eventTitle').textContent='Event unavailable';}}
async function initAuth(){const form=$('#authForm');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));try{const d=await api(form.dataset.mode==='register'?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(data)});setSession(d);const next=new URLSearchParams(location.search).get('next');location.href=next||'/dashboard.html'}catch(err){$('#formMsg').textContent=err.message;$('#formMsg').className='alert'}}}
async function initTickets(){const el=$('#orders');if(!el)return;if(!session())return location.href='/login.html';try{const {orders}=await api('/orders/mine');el.innerHTML=orders.length?orders.map(o=>`<a class="ticket card" href="/ticket.html?id=${o._id}"><div class="row between"><strong>${o.orderNumber}</strong><span class="badge green">${o.status}</span></div><h3>${escapeHtml(o.event?.title||'Event')}</h3><div class="muted">${escapeHtml(o.event?.date||'')} · ${escapeHtml(o.event?.venue||'')}</div><strong>${money(o.total,o.currency)}</strong></a>`).join(''):'<div class="empty">You have no orders yet.</div>'}catch(e){el.innerHTML=`<div class="alert">${escapeHtml(e.message)}</div>`}}
async function initTicket(){if(!$('#orderNumber'))return;const id=new URLSearchParams(location.search).get('id');if(!id)return;try{const {order:o}=await api('/orders/'+id);$('#orderNumber').textContent=o.orderNumber;$('#ticketEvent').textContent=o.event.title;$('#ticketMeta').textContent=`${o.event.date} · ${o.event.time} · ${o.event.venue}, ${o.event.city}`;$('#ticketItems').innerHTML=o.items.map(i=>`<div class="ticket"><strong>${escapeHtml(i.label)}</strong><div class="muted">Section ${escapeHtml(i.section||'-')} · Row ${escapeHtml(i.row||'-')} · Seat ${escapeHtml(i.seat||'-')}</div></div>`).join('');$('#ticketTotal').textContent=money(o.total,o.currency)}catch(e){$('#ticketEvent').textContent='Ticket unavailable'}}
async function initProfile(){const el=$('#profileForm');if(!el)return;if(!session())return location.href='/login.html';try{const {user}=await api('/auth/me');el.name.value=user.name;el.email.value=user.email;$('#profileRole').textContent=user.role;el.onsubmit=e=>{e.preventDefault();alert('Profile loaded. Account editing can be connected to your preferred auth policy.')}}catch(e){alert(e.message)}}
function boot(){nav();const search=$('#searchInput');if(search)$('#searchForm').onsubmit=e=>{e.preventDefault();loadEvents('#eventGrid',search.value)};loadEvents();loadGiveaways();initEventDetails();initAuth();initTickets();initTicket();initProfile();}
document.addEventListener('DOMContentLoaded',boot);window.TW={api,session,logout,loadEvents,loadGiveaways,money,escapeHtml};
