// TICKETWAVES - production registration
const API="https://ticketwaves-backend-3.onrender.com/api";
const countries=["Afghanistan","Albania","Algeria","Argentina","Australia","Austria","Belgium","Brazil","Canada","China","Denmark","Egypt","Finland","France","Germany","Ghana","Greece","India","Indonesia","Ireland","Italy","Japan","Kenya","Mexico","Netherlands","New Zealand","Nigeria","Norway","Philippines","Portugal","Saudi Arabia","Singapore","South Africa","South Korea","Spain","Sweden","Switzerland","Thailand","United Arab Emirates","United Kingdom","United States","Other"];
function el(...ids){for(const id of ids){const x=document.getElementById(id);if(x)return x;}return null;}
function msg(text,ok=false){let box=el("registerMessage","message","errorMessage");if(!box){box=document.createElement("div");box.id="registerMessage";document.querySelector("form")?.prepend(box);}box.textContent=text;box.style.padding="12px";box.style.margin="10px 0";box.style.borderRadius="10px";box.style.background=ok?"#e9f9ef":"#fff0f0";box.style.color=ok?"#137333":"#b42318";}
function countryField(){return el("registerCountry","country")||document.querySelector('select[name="country"]');}
function populateCountries(){const c=countryField();if(!c||c.tagName!=="SELECT")return;if(c.options.length>1)return;c.innerHTML='<option value="">Select country</option>'+countries.map(x=>`<option value="${x}">${x}</option>`).join("");}
async function doRegister(e){e?.preventDefault();const f=e?.target||document.querySelector("form");const first=(el("registerFirst","firstName","first_name")?.value||"").trim();const surname=(el("registerSurname","surname","lastName","last_name")?.value||"").trim();const phone=(el("registerPhone","phone","phoneNumber")?.value||"").trim();const country=(countryField()?.value||localStorage.getItem("ticketwaves_country")||"").trim();const email=(el("registerEmail","email")?.value||"").trim().toLowerCase();const password=el("registerPassword","password")?.value||"";if(!first||!surname||!phone||!country||!email||!password){msg("Please complete first name, surname, phone, country, email and password.");return;}if(password.length<6){msg("Password must be at least 6 characters.");return;}const btn=f?.querySelector('button[type=submit],button:not([type])');if(btn){btn.disabled=true;btn.dataset.old=btn.textContent;btn.textContent="Creating account…";}try{const r=await fetch(API+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:first,surname,phone,country,email,password})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.success)throw new Error(d.message||"Registration failed");localStorage.setItem("token",d.token);localStorage.setItem("ticketwaves_token",d.token);localStorage.setItem("user",JSON.stringify(d.user));msg("Account created successfully. Welcome to TicketWAVES!",true);setTimeout(()=>location.href="index.html",250);}catch(err){msg(err.message||"Unable to create account");if(btn){btn.disabled=false;btn.textContent=btn.dataset.old||"Create account";}}}
window.registerUser=doRegister;document.addEventListener("DOMContentLoaded",()=>{populateCountries();const f=document.querySelector("form");if(f&&!f.getAttribute("onsubmit")){f.addEventListener("submit",doRegister);}});
