
const KEY='staticTicketApp_v1';
const nowDate=new Date();
const demoTicket={
 id:'demo-ticket-1',eventName:"BTS WORLD TOUR 'ARIRANG' IN TORONTO",artistName:'BTS',
 venue:'Rogers Stadium',location:'Toronto, ON',date:'2026-08-23',time:'20:00',
 eventImage:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
 mapImage:'',orderNumber:'301272737374747345',barcodeNumber:'123456789012',
 tickets:[{id:'seat-1',eventName:"BTS WORLD TOUR 'ARIRANG' IN TORONTO",artistName:'BTS',
 venue:'Rogers Stadium',location:'Toronto, ON',date:'2026-08-23',time:'20:00',
 ticketType:'Mobile',entryInfo:'',purchaseDate:'2026-01-01',section:'D2',row:'15',seat:'3',
 eventImage:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
 orderNumber:'301272737374747345',barcodeNumber:'123456789012'}]
};
const defaultEvents=[
 {title:'My Chemical Romance',category:'Concerts',image:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=900&q=80',meta:'BE THERE LIVE'},
 {title:'J. Cole',category:'HIP-HOP/RAP',image:'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=900&q=80',meta:'LIVE'},
 {title:'World Events',category:'WORLD',image:'https://images.unsplash.com/photo-1459749411177-047381bb3ece?w=900&q=80',meta:'LIVE'}
];
const countries=[['US','United States','🇺🇸'],['CA','Canada','🇨🇦'],['GB','United Kingdom','🇬🇧'],['BE','Belgium','🇧🇪'],['AU','Australia','🇦🇺'],['DE','Germany','🇩🇪'],['FR','France','🇫🇷'],['ES','Spain','🇪🇸'],['IE','Ireland','🇮🇪'],['MX','México','🇲🇽'],['NL','Nederland','🇳🇱'],['NZ','New Zealand','🇳🇿'],['NO','Norge','🇳🇴'],['AT','Österreich','🇦🇹'],['PL','Polska','🇵🇱'],['CH','Switzerland','🇨🇭'],['AE','United Arab Emirates','🇦🇪'],['ZA','South Africa','🇿🇦'],['FI','Suomi','🇫🇮'],['SE','Sverige','🇸🇪']];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{tickets:[demoTicket],transfers:[],sales:[],user:{firstName:'Regina',lastName:'',email:'regina568@gmail.com',phone:'',country:'US',location:'Los Angeles, CA'},country:'US'}}catch{return {tickets:[demoTicket],transfers:[],sales:[],user:{firstName:'Regina',lastName:'',email:'regina568@gmail.com',phone:'',country:'US',location:'Los Angeles, CA'},country:'US'}}}
let state=load(); function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function route(){const h=location.hash.replace(/^#/,'')||'/discover'; return h}
function go(h){location.hash=h}
function fmtDate(s){const d=new Date(s+'T12:00:00');return d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'2-digit',year:'numeric'}).toUpperCase()}
function fmtTime(s){if(!s)return'';let [h,m]=s.split(':');h=+h;return `${h%12||12}:${m} ${h>=12?'PM':'AM'}`}
function nav(active,hide=false){if(hide)return'';const items=[['/discover','⌕','Discover'],['/favorites','♥','For You'],['/my-tickets','▣','My Tickets'],['/sell','▤','Sell'],['/account','●','Account']];return `<nav class="bottom">${items.map(x=>`<button class="${active===x[0]?'active':''}" onclick="go('${x[0]}')"><span class="icon">${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function shell(content,active){document.getElementById('app').innerHTML=`<div class="app">${content}${nav(active)}</div>`}
function discover(){let q='';const cards=defaultEvents.map(e=>`<div class="card" data-title="${e.title.toLowerCase()}"><img src="${e.image}" alt=""><div class="card-body"><div class="muted small">${e.meta}</div><h3>${e.title}</h3><div class="muted">${e.category}</div></div></div>`).join('');shell(`<div class="top"><div class="topbar"><div class="brand"><img src="logo-t.png"><strong>Ticket Site</strong></div><button class="country" onclick="countryModal()">🇺🇸</button></div><div class="searchrow"><div class="search"><input id="search" placeholder="Artist, Event or Venue" oninput="filterDiscover(this.value)"></div></div><div class="section-tabs"><button>Concerts</button><button>Sports</button><button>Arts, Theater & Comedy</button></div></div><main><section class="page"><div class="hero"><img src="${defaultEvents[0].image}" alt=""></div><h2>Discover</h2><div id="discoverCards">${cards}</div></section></main>`,`/discover`)}
function filterDiscover(v){document.querySelectorAll('#discoverCards .card').forEach(c=>c.style.display=c.dataset.title.includes(v.toLowerCase())?'block':'none')}
function countryModal(){document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function countrySheet(){document.getElementById('modal').innerHTML='<div class="sheet"><h2>Change Location</h2>'+countries.map(c=>`<div class="row"><span>${c[2]} &nbsp; <b>${c[1]}</b></span><button onclick="setCountry('${c[0]}')">✓</button></div>`).join('')+'<button class="btn btn-full btn-outline" onclick="closeModal()">Close</button></div>'}
function setCountry(c){state.country=c;state.user.country=c;save();closeModal();render()}
function renderCountryModal(){document.body.insertAdjacentHTML('beforeend','<div id="modal" class="modal" onclick="if(event.target.id===\'modal\')closeModal()"></div>');countrySheet()}
function myTickets(){const upcoming=state.tickets.filter(t=>new Date(t.date+'T23:59:00')>=new Date());shell(`<div class="top"><div class="topbar"><h2 style="margin:0">My Events</h2><button class="country" onclick="countryModal()">🇺🇸</button><span>Help</span></div><div class="tabs"><button class="active">UPCOMING (${upcoming.length})</button><button>PAST (0)</button></div></div><main><section class="page">${upcoming.length?upcoming.map(g=>`<div class="event-card"><img src="${g.eventImage}" alt=""><div class="event-info"><div class="small">${fmtDate(g.date)} • ${fmtTime(g.time)}</div><div class="event-title">${g.eventName}</div><div class="event-meta">${g.venue} - ${g.location}</div><button class="btn btn-blue btn-full" onclick="go('/ticket/${g.id}')">View Ticket</button></div></div>`).join(''):`<div class="empty"><div class="circle">▣</div><h2>No upcoming events</h2></div>`}</section></main>`,`/my-tickets`)}
function ticketDetail(id){const g=state.tickets.find(x=>x.id===id)||state.tickets[0];shell(`<div class="top"><div class="topbar"><button class="country" onclick="history.back()">←</button><span>Help</span></div></div><main><section class="page"><div class="event-card"><img src="${g.eventImage}"><div class="event-info"><div class="small">${fmtDate(g.date)} • ${fmtTime(g.time)}</div><div class="event-title">${g.eventName}</div><div class="event-meta">${g.venue} - ${g.location}</div><button class="btn btn-blue btn-full" onclick="alert('Ticket view opened')">View Tickets</button></div></div><div class="row"><div><h2 style="margin:0">Order #${g.orderNumber}</h2><div class="muted">x${g.tickets.length} Ticket${g.tickets.length>1?'s':''}</div></div><span>⋮</span></div><div class="ticket-table"><div class="ticket-head">TICKET${g.tickets.length>1?'S':''}</div>${g.tickets.map(t=>`<div class="ticket-row"><div><div class="label">Section</div><div class="value">${t.section}</div></div><div><div class="label">Row</div><div class="value">${t.row}</div></div><div><div class="label">Seat</div><div class="value">${t.seat}</div></div></div>`).join('')}</div><h3>MORE OPTIONS</h3><div class="map"><div class="pin">📍</div><div class="floating"><button onclick="go('/transfer/${g.id}')">↗ Transfer</button><button onclick="go('/sell')">⇄ Sell</button></div></div><div style="margin-top:18px"><button class="btn btn-outline btn-full" onclick="shareGoing()">Share You're Going</button></div><div class="row"><button class="btn btn-outline" onclick="go('/discover')">Upgrade</button><button class="btn btn-blue" onclick="go('/transfer/${g.id}')">Transfer</button><button class="btn btn-outline" onclick="go('/sell')">Sell</button></div></section></main>`,`');}
function shareGoing(){if(navigator.share)navigator.share({title:'Going to the event'});else alert('Share link ready.')}
function transfer(id){const g=state.tickets.find(x=>x.id===id)||state.tickets[0];document.getElementById('app').innerHTML=`<main><section class="page"><div class="topbar"><button onclick="go('/ticket/${g.id}')" class="btn btn-outline">← Back</button><strong>TRANSFER TICKETS</strong></div><h2>1 Ticket Selected</h2><p>Section <b>${g.tickets[0].section}</b>, Row <b>${g.tickets[0].row}</b>, Seat <b>${g.tickets[0].seat}</b></p><label>First Name*</label><input id="tf" class="input" placeholder="Enter First Name"><label>Last Name*</label><input id="tl" class="input" placeholder="Enter Last Name"><label>Email*</label><input id="te" class="input" placeholder="Enter Email Address" type="email"><label>Note</label><textarea id="tn" class="input" rows="4" placeholder="Optional note"></textarea><button class="btn btn-blue btn-full" onclick="submitTransfer('${g.id}')">Forward 1 Ticket</button></section></main>`}
function submitTransfer(id){const g=state.tickets.find(x=>x.id===id);state.transfers.push({id:'tr-'+Date.now(),ticketId:id,firstName:tf.value,lastName:tl.value,email:te.value,note:tn.value,status:'sent'});save();alert('Transfer submitted');go('/my-tickets')}
function sell(){shell(`<div class="top"><div class="topbar"><div class="brand"><img src="logo-t.png"><strong>Sell</strong></div></div></div><main><section class="page"><div class="empty"><h2>SELL TICKETS</h2><p class="muted">Plans changed? List your tickets here.</p></div><button class="btn btn-blue btn-full" onclick="listTicket()">Sell Your Tickets</button><div class="menu"><div class="row"><b>🎟 Tickets I'm Selling</b><span>›</span></div><div class="row"><b>💵 Sold Tickets</b><span>›</span></div><div class="row"><b>⚠ Expired Tickets</b><span>›</span></div></div></section></main>`,`/sell`)}
function listTicket(){if(!state.tickets.length)return alert('No tickets available');state.sales.push({ticketId:state.tickets[0].id,status:'listed'});save();alert('Ticket listed for sale');}
function account(){shell(`<div class="top"><div class="page"><h1>Account</h1><h2>${state.user.firstName}</h2><div>${state.user.email}</div></div></div><main><section class="page"><h2>Notifications</h2><div class="row"><span>✉ My Notifications</span><span>›</span></div><div class="row"><span>🔔 Receive Notifications?</span><span>ON</span></div><h2>Location Settings</h2><div class="row"><span>📍 My Location</span><button class="btn btn-outline" onclick="editLocation()">Edit</button></div><div class="row"><span>🌐 My Country</span><button class="btn btn-outline" onclick="countryModal()">Edit</button></div><div class="row"><span>➤ Location Based Content</span><span>OFF</span></div><h2>Preferences</h2><div class="row"><span>♡ My Favorites</span><span>›</span></div><div class="row"><button class="btn btn-outline" onclick="editProfile()">Edit Details</button><span>›</span></div><div class="row"><span>✓ Security</span><span>›</span></div></section></main>`,`/account`)}
function editProfile(){const n=prompt('First name',state.user.firstName);if(n!==null){state.user.firstName=n;save();render()}}
function editLocation(){const n=prompt('Location',state.user.location);if(n!==null){state.user.location=n;save();render()}}
function favorites(){shell(`<main><section class="page"><h1>For You</h1><p class="muted">Your personalized events.</p><div class="card"><div class="card-body"><h3>Favorites</h3><p>Add and manage favorite events from Discover.</p></div></div></section></main>`,`/favorites`)}
function render(){const r=route();if(!document.getElementById('modal'))renderCountryModal();if(r==='/discover'||r==='/')discover();else if(r==='/my-tickets')myTickets();else if(r==='/sell')sell();else if(r==='/account')account();else if(r==='/favorites')favorites();else if(r.startsWith('/ticket/'))ticketDetail(r.split('/')[2]);else if(r.startsWith('/transfer/'))transfer(r.split('/')[2]);else discover();}
window.addEventListener('hashchange',render); render();
