(function(){
'use strict';
const KEY='ticketSiteStateV3';
const LOGO='logo-t.png';
const countries=[['US','United States','🇺🇸'],['NG','Nigeria','🇳🇬'],['GB','United Kingdom','🇬🇧'],['CA','Canada','🇨🇦'],['AU','Australia','🇦🇺'],['BE','Belgium','🇧🇪'],['DE','Germany','🇩🇪'],['FR','France','🇫🇷'],['ES','Spain','🇪🇸'],['IE','Ireland','🇮🇪'],['ZA','South Africa','🇿🇦'],['AE','United Arab Emirates','🇦🇪'],['NL','Netherlands','🇳🇱'],['JP','Japan','🇯🇵'],['KR','South Korea','🇰🇷']];
const demo={id:'demo-ticket-1',eventName:"BTS WORLD TOUR 'ARIRANG' IN TORONTO",artistName:'BTS',venue:'Rogers Stadium',location:'Toronto, ON',date:'2026-08-23',time:'20:00',eventImage:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',mapQuery:'Rogers Stadium Toronto',orderNumber:'301272737374747345',tickets:[{id:'seat-1',section:'D2',row:'15',seat:'3',ticketType:'Mobile'}]};
const defaults={tickets:[demo],transfers:[],sales:[],user:{firstName:'Regina',lastName:'',email:'',phone:'',country:'US',location:'Los Angeles, CA'},country:'US'};
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')return {...clone(defaults),...x,user:{...clone(defaults.user),...(x.user||{})}}}catch(e){}return clone(defaults)}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function h(){return location.hash.replace(/^#/,'')||'/discover'}
function go(r){location.hash=r}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateText(s){if(!s)return'';const d=new Date(s+'T12:00:00');return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).toUpperCase()}
function timeText(s){if(!s)return'';let [a,b]=s.split(':');let hr=Number(a);return `${hr%12||12}:${b} ${hr>=12?'PM':'AM'}`}
function activeNav(active){return `<nav class="bottom">${[['/discover','⌕','Discover'],['/favorites','♥','For You'],['/my-tickets','▣','My Tickets'],['/sell','$','Sell'],['/account','●','Account']].map(n=>`<button class="${active===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="navicon">${n[1]}</span>${n[2]}</button>`).join('')}</nav>`}
function render(content,active){document.getElementById('app').innerHTML=`<div class="app">${content}${activeNav(active)}</div>`}
function ensureModal(){let m=document.getElementById('modal');if(!m){m=document.createElement('div');m.id='modal';m.className='modal';m.addEventListener('click',e=>{if(e.target===m)closeModal()});document.body.appendChild(m)}return m}
function closeModal(){const m=document.getElementById('modal');if(m)m.classList.remove('show')}
function countryModal(){const m=ensureModal();m.innerHTML=`<div class="sheet"><div class="row"><h2 style="margin:0">Change Location</h2><button class="btn outline" onclick="closeModal()">Close</button></div>${countries.map(c=>`<div class="countryrow"><span>${c[2]} &nbsp; <b>${c[1]}</b></span><button class="btn outline" onclick="setCountry('${c[0]}')">Select</button></div>`).join('')}</div>`;m.classList.add('show')}
function setCountry(c){state.country=c;state.user.country=c;save();closeModal();render()}
function header(title=''){return `<div class="top"><div class="topbar"><div class="brand"><img src="${LOGO}"><strong>${esc(title||'Ticket Site')}</strong></div><button class="iconbtn" onclick="countryModal()">🌐</button></div></div>`}
function discover(){render(`${header()}<div class="top"><div class="searchrow"><div class="search"><input id="q" placeholder="Artist, Event or Venue" oninput="filterEvents(this.value)"></div></div><div class="chips"><button class="chip">Concerts</button><button class="chip">Sports</button><button class="chip">Arts, Theater & Comedy</button></div></div><main><section class="page"><div class="hero"><img src="https://images.unsplash.com/photo-1459749411177-047381bb3ece?w=1200&q=80" alt=""></div><h1>Discover</h1><div id="eventList">${eventsHtml()}</div></section></main>`,`/discover`)}
function eventsHtml(){return [{title:'My Chemical Romance',category:'Concerts',image:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1000&q=80',meta:'BE THERE LIVE'},{title:'J. Cole',category:'HIP-HOP/RAP',image:'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=1000&q=80',meta:'LIVE'},{title:'World Events',category:'WORLD',image:'https://images.unsplash.com/photo-1459749411177-047381bb3ece?w=1000&q=80',meta:'LIVE'}].map(e=>`<article class="card" data-title="${esc(e.title.toLowerCase())}"><img src="${e.image}" alt=""><div class="cardbody"><div class="muted small">${esc(e.meta)}</div><h3>${esc(e.title)}</h3><div class="muted">${esc(e.category)}</div></div></article>`).join('')}
function filterEvents(v){document.querySelectorAll('#eventList .card').forEach(c=>c.style.display=c.dataset.title.includes(v.toLowerCase())?'block':'none')}
function ticketCard(g){return `<article class="event"><img src="${esc(g.eventImage)}" alt=""><div class="eventbody"><div class="small">${dateText(g.date)} • ${timeText(g.time)}</div><div class="eventtitle">${esc(g.eventName)}</div><div class="event-meta">${esc(g.venue)} - ${esc(g.location)}</div><button class="btn blue full" onclick="go('/ticket/${encodeURIComponent(g.id)}')">View Ticket</button></div></article>`}
function myTickets(){const u=state.tickets.filter(t=>new Date(t.date+'T23:59:59')>=new Date());render(`${header('My Events')}<div class="tabs"><button class="active">UPCOMING (${u.length})</button><button>PAST (0)</button></div><main><section class="page">${u.length?u.map(ticketCard).join(''):'<div class="empty"><div class="emptyicon">▣</div><h2>No upcoming events</h2><p class="muted">Tickets you add from For You will appear here.</p></div>'}</section></main>`,`/my-tickets`)}
function ticketDetail(id){const g=state.tickets.find(t=>t.id===decodeURIComponent(id))||state.tickets[0];if(!g){myTickets();return}render(`${header()}<main><section class="page"><article class="event"><img src="${esc(g.eventImage)}" alt=""><div class="eventbody"><div class="small">${dateText(g.date)} • ${timeText(g.time)}</div><div class="eventtitle">${esc(g.eventName)}</div><div class="event-meta">${esc(g.venue)} - ${esc(g.location)}</div></div></article><div class="row"><div><h2 style="margin:0">Order #${esc(g.orderNumber)}</h2><div class="muted">x${g.tickets.length} Ticket${g.tickets.length>1?'s':''}</div></div><span>⋮</span></div>${g.tickets.map(t=>`<div class="ticketgrid"><div class="ticketcell"><div class="label">Section</div><div class="value">${esc(t.section)}</div></div><div class="ticketcell"><div class="label">Row</div><div class="value">${esc(t.row)}</div></div><div class="ticketcell"><div class="label">Seat</div><div class="value">${esc(t.seat)}</div></div></div>`).join('')}<h3>MORE OPTIONS</h3><div class="map"><iframe loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=-79.40,43.63,-79.35,43.67&layer=mapnik&marker=43.653, -79.3832"></iframe><div class="pin">📍</div><div class="floating"><button onclick="go('/transfer/${encodeURIComponent(g.id)}')">↗ Transfer</button><button onclick="go('/sell')">⇄ Sell</button></div></div><div class="row"><button class="btn outline" onclick="alert('Upgrade options')">Upgrade</button><button class="btn blue" onclick="go('/transfer/${encodeURIComponent(g.id)}')">Transfer</button><button class="btn outline" onclick="go('/sell')">Sell</button></div></section></main>`,`/my-tickets`)}
function transfer(id){const g=state.tickets.find(t=>t.id===decodeURIComponent(id))||state.tickets[0];if(!g){myTickets();return}document.getElementById('app').innerHTML=`<main><section class="page"><div class="row"><button class="btn outline" onclick="go('/ticket/${encodeURIComponent(g.id)}')">← Back</button><b>TRANSFER TICKETS</b></div><h2>1 Ticket Selected</h2><p>Section <b>${esc(g.tickets[0].section)}</b>, Row <b>${esc(g.tickets[0].row)}</b>, Seat <b>${esc(g.tickets[0].seat)}</b></p><label>First Name*</label><input id="tf" class="input"><label>Last Name*</label><input id="tl" class="input"><label>Email*</label><input id="te" class="input" type="email"><label>Note</label><textarea id="tn" class="input" rows="4"></textarea><button class="btn blue full" onclick="submitTransfer('${esc(g.id)}')">Forward 1 Ticket</button></section></main>`}
function submitTransfer(id){const g=state.tickets.find(t=>t.id===id);const f=document.getElementById('tf').value.trim(),l=document.getElementById('tl').value.trim(),e=document.getElementById('te').value.trim(),n=document.getElementById('tn').value.trim();if(!f||!l||!e){alert('Please complete required fields.');return}state.transfers.push({ticketId:id,firstName:f,lastName:l,email:e,note:n,status:'sent',createdAt:new Date().toISOString()});save();alert('Transfer submitted');go('/my-tickets')}
function sell(){render(`${header('Sell')}<main><section class="page"><div class="empty"><h2>SELL TICKETS</h2><p class="muted">List your tickets and manage your sale activity.</p></div><button class="btn blue full" onclick="listFirstTicket()">Sell Your Tickets</button>${state.sales.map(s=>`<div class="row"><span>Ticket ${esc(s.ticketId)}</span><b>${esc(s.status)}</b></div>`).join('')}</section></main>`,`/sell`)}
function listFirstTicket(){if(!state.tickets.length)return alert('No tickets available');state.sales.push({ticketId:state.tickets[0].id,status:'listed',createdAt:new Date().toISOString()});save();alert('Ticket listed for sale');render()}
function account(){render(`${header('Account')}<main><section class="page"><h2>${esc(state.user.firstName)} ${esc(state.user.lastName)}</h2><p class="muted">${esc(state.user.email||'')}</p><h3>Location Settings</h3><div class="row"><span>My Location</span><button class="btn outline" onclick="editLocation()">Edit</button></div><div class="row"><span>My Country</span><button class="btn outline" onclick="countryModal()">Edit</button></div><h3>Preferences</h3><div class="row"><span>My Favorites</span><span>›</span></div><div class="row"><button class="btn outline" onclick="editProfile()">Edit Details</button><span>›</span></div></section></main>`,`/account`)}
function editProfile(){const n=prompt('First name',state.user.firstName||'');if(n!==null){state.user.firstName=n.trim()||state.user.firstName;save();render()}}
function editLocation(){const n=prompt('Location',state.user.location||'');if(n!==null){state.user.location=n.trim()||state.user.location;save();render()}}
function favorites(){render(`${header('For You')}<main><section class="page"><h1>For You</h1><p class="muted">Your personalized events and saved preferences.</p><div class="card"><div class="cardbody"><h3>Manage your experience</h3><p>Tickets added here can be opened from My Tickets.</p><button class="btn blue" onclick="go('/my-tickets')">Open My Tickets</button></div></div></section></main>`,`/favorites`)}
function render(){try{const r=h();if(r==='/'||r==='/discover')discover();else if(r==='/my-tickets')myTickets();else if(r==='/sell')sell();else if(r==='/account')account();else if(r==='/favorites')favorites();else if(r.startsWith('/ticket/'))ticketDetail(r.slice(8));else if(r.startsWith('/transfer/'))transfer(r.slice(10));else discover()}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="error"><h2>Something went wrong</h2><p>Please refresh the page.</p></div>'}}
window.addEventListener('hashchange',render);
render();
})();