(function(){"use strict";
const KEY="ticketSiteStateV7";
const DEFAULT_IMG="https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1400&q=85";
const DEMO={id:"demo-1",eventName:"BTS WORLD TOUR 'ARIRANG' IN TORONTO",artistName:"BTS",venue:"Rogers Stadium",location:"Toronto, ON",date:"2026-08-23",time:"20:00",eventImage:DEFAULT_IMG,mapQuery:"Rogers Stadium Toronto",orderNumber:"301272737374747345",extraInfo:"TICKET",tickets:[{id:"seat-1",section:"D2",row:"15",seat:"3",ticketType:"Mobile",barcode:"301272737374747345"}]};
const defaults={tickets:[DEMO],transfers:[],sales:[],user:{firstName:"Regina",lastName:"",email:"",phone:"",country:"US"},country:"US"};
function clone(x){return JSON.parse(JSON.stringify(x))} function uid(p){return p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8)}
function load(){try{let r=JSON.parse(localStorage.getItem(KEY));if(r&&typeof r==="object")return {...clone(defaults),...r,tickets:Array.isArray(r.tickets)?r.tickets:clone(defaults.tickets),transfers:Array.isArray(r.transfers)?r.transfers:[],sales:Array.isArray(r.sales)?r.sales:[],user:{...clone(defaults.user),...(r.user||{})}}}catch(e){}return clone(defaults)}
let state=load();function save(){localStorage.setItem(KEY,JSON.stringify(state))} function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function route(){return location.hash.replace(/^#/,'')||'/discover'} function go(x){location.hash=x} function val(id){return document.getElementById(id)?.value.trim()||""}
function fmtDate(s){if(!s)return"";let d=new Date(s+"T12:00:00");return isNaN(d)?esc(s):d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).toUpperCase()} function fmtTime(s){if(!s)return"";let a=String(s).split(':');let h=+a[0];return (h%12||12)+':'+a[1]+' '+(h>=12?'PM':'AM')}
function ensureModal(){return document.getElementById('modal')} function closeModal(){let m=ensureModal();m.className='modal';m.innerHTML=''}
function header(title){return `<header class="darkHeader"><div class="headerBar"><div class="headerSide"><button class="iconBtn" onclick="go('/discover')">‹</button></div><div class="brand"><img src="logo-t.png" alt=""><span>${esc(title||'')}</span></div><div class="headerSide right"><button class="iconBtn" onclick="alert('Help')">Help</button></div></div></header>`}
function bottom(a){return `<nav class="bottomNav"><button class="${a==='/discover'?'active':''}" onclick="go('/discover')"><span class="navIcon">⌕</span><span class="navText">Discover</span></button><button class="${a==='/favorites'?'active':''}" onclick="go('/favorites')"><span class="navIcon">♥</span><span class="navText">For You</span></button><button class="${a==='/my-tickets'?'active':''}" onclick="go('/my-tickets')"><span class="navIcon">◈</span><span class="navText">My Tickets</span></button><button class="${a==='/sell'?'active':''}" onclick="go('/sell')"><span class="navIcon">$</span><span class="navText">Sell</span></button><button class="${a==='/account'?'active':''}" onclick="go('/account')"><span class="navIcon">●</span><span class="navText">Account</span></button></nav>`}
function renderShell(content,active){document.getElementById('app').innerHTML=`<div class="app"><div class="shell">${content}</div>${bottom(active)}</div>`}
function discover(){renderShell(`${header('Discover')}<div class="searchArea"><div class="searchBox"><input placeholder="Artist, Event or Venue"></div><div class="chips"><button class="chip">Concerts</button><button class="chip">Sports</button><button class="chip">Arts & Comedy</button></div></div><main class="page"><div class="eventList">${['My Chemical Romance','J. Cole','World Events'].map((x,i)=>`<article class="infoCard"><div style="font-size:12px;color:#777;font-weight:800">LIVE</div><h2>${x}</h2><p class="muted">Entertainment</p></article>`).join('')}</div></main>`,`/discover`)}
function myTickets(tab='upcoming'){let now=new Date();let upcoming=state.tickets.filter(t=>new Date((t.date||'9999-12-31')+'T23:59:59')>=now),past=state.tickets.filter(t=>!upcoming.includes(t)),items=tab==='past'?past:upcoming;renderShell(`${header('My Events')}<div class="tabHeader"><div class="tabs"><button class="${tab==='upcoming'?'active':''}" onclick="myTickets('upcoming')">UPCOMING (${upcoming.length})</button><button class="${tab==='past'?'active':''}" onclick="myTickets('past')">PAST (${past.length})</button></div></div><main class="page">${items.length?items.map(myEvent).join(''):`<div class="emptyPage"><h2>No ${tab} events</h2><p class="muted">Tickets added from For You appear here automatically.</p></div>`}</main>`,`/my-tickets`)}
function myEvent(g){return `<article class="myEventCard"><div class="eventHero"><img src="${esc(g.eventImage||DEFAULT_IMG)}" alt=""></div><div class="eventInfoOverlay"><div class="eventDate">${fmtDate(g.date)} • ${fmtTime(g.time)} <span class="countBadge">▧ x${g.tickets.length}</span></div><div class="eventName">${esc(g.eventName)}</div><div class="eventMeta">${esc(g.venue)} - ${esc(g.location)}</div></div><button class="viewBtn" onclick="go('/ticket/${encodeURIComponent(g.id)}')">▦ View Tickets</button></article>`}
function ticketDetail(id){
 let g=state.tickets.find(x=>x.id===decodeURIComponent(id)); if(!g)return myTickets();
 const tcount=g.tickets.length;
 const detail=`<article class="myEventCard"><div class="eventHero"><img src="${esc(g.eventImage||DEFAULT_IMG)}" alt=""></div><div class="eventInfoOverlay"><div class="eventDate">${fmtDate(g.date)} • ${fmtTime(g.time)} <span class="countBadge">▣ x${tcount}</span></div><div class="eventName">${esc(g.eventName)}</div><div class="eventMeta">${esc(g.venue)} - ${esc(g.location)}</div></div><button class="viewBtn" onclick="showBarcode('${encodeURIComponent(g.id)}')">▥ View Tickets</button></article>`;
 const seats=g.tickets.map((t,i)=>seatCard(g,t,i)).join('');
 const content=`${header('')}<main class="page"><div class="ticketTabs"><button class="tabOn" onclick="switchTicketTab(this,'ticketsPanel','extrasPanel')">Tickets</button><button onclick="switchTicketTab(this,'extrasPanel','ticketsPanel')">Extras</button></div><div id="ticketsPanel" class="tabBody">${detail}<div class="orderBlock"><div class="orderRow"><div><div class="orderTitle">Order #${esc(g.orderNumber)}</div><div class="orderSub">x${tcount} Ticket${tcount===1?'':'s'}</div></div><button class="iconBtn more" onclick="alert('More options')">⋮</button></div>${seats}<div class="moreOptions">MORE OPTIONS</div><div class="mapWrap"><iframe title="Venue map" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=-79.42%2C43.63%2C-79.32%2C43.70&layer=mapnik&marker=43.8078%2C-79.3449"></iframe><div class="mapPill"><button onclick="alert('Upgrade options')">↥ Upgrade</button><button onclick="openTransfer('${encodeURIComponent(g.id)}')">↗ Transfer</button><button onclick="sellTicket('${encodeURIComponent(g.id)}')">⟳ Sell</button></div></div><a class="directionsBtn" target="_blank" rel="noopener" href="https://www.openstreetmap.org/search?query=${encodeURIComponent((g.venue||'')+' '+(g.location||''))}">Get Directions</a></div></div><div id="extrasPanel" class="extrasPanel"><div class="gotTicketCard"><div class="gotTicketImage"><img src="${esc(g.eventImage||DEFAULT_IMG)}" alt=""><div class="gotTicketText">YOU GOT<br>TICKETS!</div></div><div class="socialText"><h3>Post on Social Media</h3><p>Build hype for the event, and share that you got tickets with your friends and family.</p></div></div></div></main>`;
 renderShell(content,'/my-tickets');
}
function switchTicketTab(btn,showId,hideId){document.querySelectorAll('.ticketTabs button').forEach(b=>b.classList.remove('tabOn'));btn.classList.add('tabOn');document.getElementById(showId).classList.add('show');document.getElementById(hideId).classList.remove('show')}
function seatCard(g,t,i){let p=state.transfers.find(x=>x.ticketId===g.id&&x.ticketIndex===i&&x.status==='pending');return `<div class="ticketCard"><div class="ticketHead">${esc(g.extraInfo||'TICKET')}</div><div class="ticketSeats"><div class="ticketSeat"><div class="ticketLabel">SECTION</div><div class="ticketValue">${esc(t.section||'—')}</div></div><div class="ticketSeat"><div class="ticketLabel">ROW</div><div class="ticketValue">${esc(t.row||'—')}</div></div><div class="ticketSeat"><div class="ticketLabel">SEAT</div><div class="ticketValue">${esc(t.seat||'—')}</div></div></div>${p?`<div class="transferPending"><div class="transferText"><span class="statusIcon">↗</span><span>Transfer Pending: ${esc(p.firstName+' '+p.lastName)}</span></div><button class="deleteBtn" onclick="cancelTransfer('${encodeURIComponent(g.id)}',${i})">♜</button></div>`:''}</div>`}
function showBarcode(id){let g=state.tickets.find(x=>x.id===decodeURIComponent(id));if(!g)return;let m=ensureModal();m.className='modal show barcodeModal';m.innerHTML=`<div class="sheet"><div class="sheetHandle"></div><div class="sheetHeader">Tickets <button class="secondaryBtn" style="float:right" onclick="closeModal()">Done</button></div><div class="barcodeSheet">${g.tickets.map(t=>`<div style="padding:18px 0"><div class="ticketHead">TICKET</div><div class="barcodeBars"></div><div class="barcodeNumber">${esc(t.barcode||g.orderNumber||t.id)}</div></div>`).join('')}</div></div>`}
function openTransfer(id){let g=state.tickets.find(x=>x.id===decodeURIComponent(id));if(!g)return;let m=ensureModal();let t=g.tickets[0]||{};m.className='modal show';m.innerHTML=`<div class="sheet"><div class="sheetHandle"></div><div class="sheetHeader">TRANSFER TICKETS</div><div class="transferSheetBody"><h2 style="margin:0 0 6px">1 Ticket Selected</h2><div class="transferSeat">Section <b>${esc(t.section)}</b>, Row <b>${esc(t.row)}</b>, Seat <b>${esc(t.seat)}</b></div><div class="transferLabel">First Name*</div><input class="transferInput" id="tf" placeholder="Enter First Name"><div class="transferLabel">Last Name*</div><input class="transferInput" id="tl" placeholder="Enter Last Name"><div class="transferLabel">Email*</div><input class="transferInput" id="te" type="email" placeholder="Enter Email Address"><div class="transferSwitch">Use Mobile Number Instead</div><div class="transferLabel">Note</div><textarea class="transferInput" id="tn" style="height:88px;padding-top:12px" placeholder=""></textarea></div><div class="transferFooter"><button class="transferBack" onclick="closeModal()">‹ Back</button><button class="transferForward" onclick="submitTransfer('${encodeURIComponent(g.id)}')">Forward 1 Ticket</button></div></div>`}
function submitTransfer(id){let d=decodeURIComponent(id),g=state.tickets.find(x=>x.id===d);let f=val('tf'),l=val('tl'),e=val('te'),n=val('tn');if(!f||!l||!e){alert('Please complete the required fields.');return}state.transfers.push({id:uid('transfer'),ticketId:d,ticketIndex:0,firstName:f,lastName:l,email:e,note:n,status:'pending'});save();closeModal();go('/ticket/'+encodeURIComponent(d))}
function cancelTransfer(id,i){let d=decodeURIComponent(id);state.transfers=state.transfers.filter(x=>!(x.ticketId===d&&x.ticketIndex===i));save();ticketDetail(encodeURIComponent(d))}
function sellTicket(id){let d=decodeURIComponent(id);state.sales.push({id:uid('sale'),ticketId:d,status:'listed'});save();alert('Ticket listed for sale')}
function addTicket(){document.getElementById('app').innerHTML=`<div class="app"><div class="shell"><div class="formPage">${ticketForm()}</div></div></div>`}
function editTicket(id){let g=state.tickets.find(x=>x.id===decodeURIComponent(id));if(g)document.getElementById('app').innerHTML=`<div class="app"><div class="shell"><div class="formPage">${ticketForm(g)}</div></div></div>`}
function ticketForm(g){let x=g||{id:'',eventName:'',artistName:'',venue:'',location:'',date:'',time:'20:00',orderNumber:'',extraInfo:'TICKET',eventImage:'',mapQuery:'',tickets:[{section:'',row:'',seat:'',barcode:''}]};let ts=x.tickets?.length?x.tickets:[{section:'',row:'',seat:'',barcode:''}];return `<div class="formRow"><button class="secondaryBtn" onclick="go('/favorites')">← Back</button><div class="formTitle">${x.id?'Edit':'Add'} Ticket</div><span></span></div><form onsubmit="saveTicket(event)"><input type="hidden" id="editId" value="${esc(x.id)}"><label class="label">Event Name*</label><input class="input" id="fEvent" required value="${esc(x.eventName)}"><label class="label">Artist / Performer</label><input class="input" id="fArtist" value="${esc(x.artistName)}"><label class="label">Venue*</label><input class="input" id="fVenue" required value="${esc(x.venue)}"><label class="label">Location*</label><input class="input" id="fLocation" required value="${esc(x.location)}"><label class="label">Date*</label><input class="input" id="fDate" type="date" required value="${esc(x.date)}"><label class="label">Time</label><input class="input" id="fTime" type="time" value="${esc(x.time)}"><label class="label">Order Number</label><input class="input" id="fOrder" value="${esc(x.orderNumber)}"><label class="label">Ticket header / extra info</label><input class="input" id="fExtra" value="${esc(x.extraInfo||'TICKET')}"><label class="label">Event image</label><div class="imageUpload"><input class="input" id="fImageFile" type="file" accept="image/*" onchange="previewImage(this)"><input class="input" id="fImageUrl" type="url" placeholder="Or paste image URL"><img id="imagePreview" class="previewImg" src="${esc(x.eventImage||'')}" ${x.eventImage?'':'style="display:none"'}></div><label class="label">Map search</label><input class="input" id="fMap" value="${esc(x.mapQuery||x.location||x.venue)}"><div class="formRow" style="margin-top:22px"><div class="formTitle">Tickets / Seats</div><button class="secondaryBtn" type="button" onclick="addSeatEditor()">+ Add seat</button></div><div id="seatEditors">${ts.map(seatEditor).join('')}</div><button class="primaryBtn full" type="submit">Save Ticket</button>${x.id?`<button class="secondaryBtn full" type="button" style="margin-top:10px;color:#c62828" onclick="deleteTicket('${encodeURIComponent(x.id)}')">Delete Ticket</button>`:''}</form>`}
function seatEditor(t,i){return `<div class="ticketRowEditor"><div class="ticketRowTop"><span>Seat ${i+1}</span>${i?`<button type="button" class="smallDanger" onclick="this.closest('.ticketRowEditor').remove()">Remove</button>`:''}</div><div class="rowGrid"><div><label class="label">Section</label><input class="input seatSection" value="${esc(t.section||'')}"></div><div><label class="label">Row</label><input class="input seatRow" value="${esc(t.row||'')}"></div><div><label class="label">Seat</label><input class="input seatSeat" value="${esc(t.seat||'')}"></div></div><label class="label">Barcode / Ticket number</label><input class="input seatBarcode" value="${esc(t.barcode||'')}"><input type="hidden" class="seatId" value="${esc(t.id||uid('seat'))}"></div>`}
function addSeatEditor(){let b=document.getElementById('seatEditors');b.insertAdjacentHTML('beforeend',seatEditor({section:'',row:'',seat:'',barcode:''},b.children.length))}
function previewImage(inp){let f=inp.files?.[0];if(!f)return;let r=new FileReader();r.onload=e=>{let p=document.getElementById('imagePreview');p.src=e.target.result;p.style.display='block'};r.readAsDataURL(f)}
function saveTicket(ev){ev.preventDefault();let id=val('editId'),existing=state.tickets.find(x=>x.id===id),image=document.getElementById('imagePreview')?.src||val('fImageUrl')||existing?.eventImage||DEFAULT_IMG;let tickets=[...document.querySelectorAll('#seatEditors .ticketRowEditor')].map(el=>({id:el.querySelector('.seatId')?.value||uid('seat'),section:el.querySelector('.seatSection')?.value.trim()||'',row:el.querySelector('.seatRow')?.value.trim()||'',seat:el.querySelector('.seatSeat')?.value.trim()||'',barcode:el.querySelector('.seatBarcode')?.value.trim()||'',ticketType:'Mobile'})).filter(t=>t.section||t.row||t.seat||t.barcode);if(!tickets.length)tickets=[{id:uid('seat'),section:'',row:'',seat:'',barcode:'',ticketType:'Mobile'}];let g={id:id||uid('ticket'),eventName:val('fEvent'),artistName:val('fArtist'),venue:val('fVenue'),location:val('fLocation'),date:val('fDate'),time:val('fTime')||'20:00',orderNumber:val('fOrder')||uid('order').replace(/-/g,''),extraInfo:val('fExtra')||'TICKET',eventImage:image,mapQuery:val('fMap')||val('fLocation'),tickets};if(existing)state.tickets=state.tickets.map(x=>x.id===id?g:x);else state.tickets.unshift(g);save();go('/my-tickets')}
function deleteTicket(id){let d=decodeURIComponent(id);if(!confirm('Delete this ticket?'))return;state.tickets=state.tickets.filter(x=>x.id!==d);state.transfers=state.transfers.filter(x=>x.ticketId!==d);state.sales=state.sales.filter(x=>x.ticketId!==d);save();go('/my-tickets')}
function favorites(){document.getElementById('app').innerHTML=`<div class="app"><div class="shell">${header('For You')}<main class="foryouPage"><div class="infoCard"><h2 style="margin-top:0">For You</h2><p class="muted">Add and manage your ticket details here. Saved tickets automatically appear in My Tickets.</p><button class="primaryBtn full" onclick="addTicket()">+ Add Ticket</button></div>${state.tickets.map(g=>`<div class="infoCard"><b>${esc(g.eventName)}</b><p class="muted">${fmtDate(g.date)} • ${esc(g.venue)} • ${g.tickets.length} ticket${g.tickets.length===1?'':'s'}</p><div style="display:flex;gap:10px"><button class="secondaryBtn" onclick="editTicket('${encodeURIComponent(g.id)}')">Edit</button><button class="secondaryBtn" onclick="go('/ticket/${encodeURIComponent(g.id)}')">View</button></div></div>`).join('')}</main></div>${bottom('/favorites')}</div>`}
function sell(){renderShell(`${header('Sell')}<main class="foryouPage">${state.tickets.map(g=>`<div class="infoCard"><b>${esc(g.eventName)}</b><p class="muted">${fmtDate(g.date)} • ${esc(g.venue)}</p><button class="primaryBtn" onclick="sellTicket('${encodeURIComponent(g.id)}')">List Ticket</button></div>`).join('')}</main>`,`/sell`)}
function account(){renderShell(`${header('Account')}<main class="foryouPage"><div class="infoCard"><h2>${esc(state.user.firstName)} ${esc(state.user.lastName)}</h2><p class="muted">${esc(state.user.email||'')}</p><button class="secondaryBtn" onclick="editProfile()">Edit Profile</button></div></main>`,`/account`)} function editProfile(){let n=prompt('First name',state.user.firstName||'');if(n!==null){state.user.firstName=n.trim()||state.user.firstName;save();render()}}
function render(){try{let r=route();if(r==='/discover')discover();else if(r==='/favorites')favorites();else if(r==='/my-tickets')myTickets();else if(r==='/sell')sell();else if(r==='/account')account();else if(r.startsWith('/ticket/'))ticketDetail(r.slice(8));else discover()}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="errorPage"><h2>App error</h2><p>'+esc(e.message||'Please refresh')+'</p></div>'}}
window.go=go;window.myTickets=myTickets;window.addTicket=addTicket;window.editTicket=editTicket;window.saveTicket=saveTicket;window.deleteTicket=deleteTicket;window.addSeatEditor=addSeatEditor;window.previewImage=previewImage;window.openTransfer=openTransfer;window.submitTransfer=submitTransfer;window.cancelTransfer=cancelTransfer;window.sellTicket=sellTicket;window.showBarcode=showBarcode;window.closeModal=closeModal;window.editProfile=editProfile;window.render=render;window.addEventListener('hashchange',render);render();
})();