import type { Country } from '../types';

export const allCountries: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", language: "fa", languageName: "Farsi" },
  { code: "AL", name: "Albania", flag: "🇦🇱", language: "sq", languageName: "Albanian" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", language: "ar", languageName: "Arabic" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", language: "ca", languageName: "Catalan" },
  { code: "AO", name: "Angola", flag: "🇦🇴", language: "pt", languageName: "Portuguese" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", language: "en", languageName: "English" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", language: "es", languageName: "Spanish" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", language: "hy", languageName: "Armenian" },
  { code: "AU", name: "Australia", flag: "🇦🇺", language: "en", languageName: "English" },
  { code: "AT", name: "Austria", flag: "🇦🇹", language: "de", languageName: "German" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", language: "az", languageName: "Azerbaijani" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", language: "en", languageName: "English" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", language: "ar", languageName: "Arabic" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", language: "bn", languageName: "Bengali" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", language: "en", languageName: "English" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", language: "be", languageName: "Belarusian" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", language: "nl", languageName: "Dutch" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", language: "en", languageName: "English" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", language: "fr", languageName: "French" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", language: "dz", languageName: "Dzongkha" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", language: "es", languageName: "Spanish" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", language: "bs", languageName: "Bosnian" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", language: "en", languageName: "English" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", language: "pt", languageName: "Portuguese" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", language: "ms", languageName: "Malay" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", language: "bg", languageName: "Bulgarian" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", language: "fr", languageName: "French" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", language: "rn", languageName: "Kirundi" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", language: "pt", languageName: "Portuguese" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", language: "km", languageName: "Khmer" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", language: "fr", languageName: "French" },
  { code: "CA", name: "Canada", flag: "🇨🇦", language: "en", languageName: "English" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", language: "fr", languageName: "French" },
  { code: "TD", name: "Chad", flag: "🇹🇩", language: "fr", languageName: "French" },
  { code: "CL", name: "Chile", flag: "🇨🇱", language: "es", languageName: "Spanish" },
  { code: "CN", name: "China", flag: "🇨🇳", language: "zh", languageName: "Chinese" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", language: "es", languageName: "Spanish" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", language: "ar", languageName: "Arabic" },
  { code: "CG", name: "Congo", flag: "🇨🇬", language: "fr", languageName: "French" },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", language: "fr", languageName: "French" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", language: "es", languageName: "Spanish" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", language: "hr", languageName: "Croatian" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", language: "es", languageName: "Spanish" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", language: "el", languageName: "Greek" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", language: "cs", languageName: "Czech" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", language: "da", languageName: "Danish" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", language: "fr", languageName: "French" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", language: "en", languageName: "English" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", language: "es", languageName: "Spanish" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", language: "es", languageName: "Spanish" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", language: "ar", languageName: "Arabic" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", language: "es", languageName: "Spanish" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", language: "es", languageName: "Spanish" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", language: "ti", languageName: "Tigrinya" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", language: "et", languageName: "Estonian" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", language: "en", languageName: "English" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", language: "am", languageName: "Amharic" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", language: "en", languageName: "English" },
  { code: "FI", name: "Finland", flag: "🇫🇮", language: "fi", languageName: "Finnish" },
  { code: "FR", name: "France", flag: "🇫🇷", language: "fr", languageName: "French" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", language: "fr", languageName: "French" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", language: "en", languageName: "English" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", language: "ka", languageName: "Georgian" },
  { code: "DE", name: "Germany", flag: "🇩🇪", language: "de", languageName: "German" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", language: "en", languageName: "English" },
  { code: "GR", name: "Greece", flag: "🇬🇷", language: "el", languageName: "Greek" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", language: "en", languageName: "English" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", language: "es", languageName: "Spanish" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", language: "fr", languageName: "French" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", language: "pt", languageName: "Portuguese" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", language: "en", languageName: "English" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", language: "ht", languageName: "Haitian Creole" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", language: "es", languageName: "Spanish" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", language: "hu", languageName: "Hungarian" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", language: "is", languageName: "Icelandic" },
  { code: "IN", name: "India", flag: "🇮🇳", language: "hi", languageName: "Hindi" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", language: "id", languageName: "Indonesian" },
  { code: "IR", name: "Iran", flag: "🇮🇷", language: "fa", languageName: "Farsi" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", language: "ar", languageName: "Arabic" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", language: "en", languageName: "English" },
  { code: "IL", name: "Israel", flag: "🇮🇱", language: "he", languageName: "Hebrew" },
  { code: "IT", name: "Italy", flag: "🇮🇹", language: "it", languageName: "Italian" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", language: "en", languageName: "English" },
  { code: "JP", name: "Japan", flag: "🇯🇵", language: "ja", languageName: "Japanese" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", language: "ar", languageName: "Arabic" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", language: "kk", languageName: "Kazakh" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", language: "sw", languageName: "Swahili" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", language: "en", languageName: "English" },
  { code: "KP", name: "Korea (North)", flag: "🇰🇵", language: "ko", languageName: "Korean" },
  { code: "KR", name: "Korea (South)", flag: "🇰🇷", language: "ko", languageName: "Korean" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", language: "ar", languageName: "Arabic" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", language: "ky", languageName: "Kyrgyz" },
  { code: "LA", name: "Laos", flag: "🇱🇦", language: "lo", languageName: "Lao" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", language: "lv", languageName: "Latvian" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", language: "ar", languageName: "Arabic" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", language: "en", languageName: "English" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", language: "en", languageName: "English" },
  { code: "LY", name: "Libya", flag: "🇱🇾", language: "ar", languageName: "Arabic" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", language: "de", languageName: "German" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", language: "lt", languageName: "Lithuanian" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", language: "lb", languageName: "Luxembourgish" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", language: "mg", languageName: "Malagasy" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", language: "en", languageName: "English" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", language: "ms", languageName: "Malay" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", language: "dv", languageName: "Dhivehi" },
  { code: "ML", name: "Mali", flag: "🇲🇱", language: "fr", languageName: "French" },
  { code: "MT", name: "Malta", flag: "🇲🇹", language: "mt", languageName: "Maltese" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", language: "en", languageName: "English" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", language: "ar", languageName: "Arabic" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", language: "en", languageName: "English" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", language: "es", languageName: "Spanish" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", language: "en", languageName: "English" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", language: "ro", languageName: "Romanian" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", language: "fr", languageName: "French" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", language: "mn", languageName: "Mongolian" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", language: "sr", languageName: "Serbian" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", language: "ar", languageName: "Arabic" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", language: "pt", languageName: "Portuguese" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", language: "my", languageName: "Burmese" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", language: "en", languageName: "English" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", language: "en", languageName: "English" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", language: "ne", languageName: "Nepali" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", language: "nl", languageName: "Dutch" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", language: "en", languageName: "English" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", language: "es", languageName: "Spanish" },
  { code: "NE", name: "Niger", flag: "🇳🇪", language: "fr", languageName: "French" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", language: "en", languageName: "English" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", language: "mk", languageName: "Macedonian" },
  { code: "NO", name: "Norway", flag: "🇳🇴", language: "no", languageName: "Norwegian" },
  { code: "OM", name: "Oman", flag: "🇴🇲", language: "ar", languageName: "Arabic" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", language: "ur", languageName: "Urdu" },
  { code: "PW", name: "Palau", flag: "🇵🇼", language: "en", languageName: "English" },
  { code: "PA", name: "Panama", flag: "🇵🇦", language: "es", languageName: "Spanish" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", language: "en", languageName: "English" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", language: "es", languageName: "Spanish" },
  { code: "PE", name: "Peru", flag: "🇵🇪", language: "es", languageName: "Spanish" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", language: "tl", languageName: "Tagalog" },
  { code: "PL", name: "Poland", flag: "🇵🇱", language: "pl", languageName: "Polish" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", language: "pt", languageName: "Portuguese" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", language: "ar", languageName: "Arabic" },
  { code: "RO", name: "Romania", flag: "🇷🇴", language: "ro", languageName: "Romanian" },
  { code: "RU", name: "Russia", flag: "🇷🇺", language: "ru", languageName: "Russian" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", language: "rw", languageName: "Kinyarwanda" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", language: "en", languageName: "English" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", language: "en", languageName: "English" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", language: "en", languageName: "English" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", language: "sm", languageName: "Samoan" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", language: "it", languageName: "Italian" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", language: "pt", languageName: "Portuguese" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", language: "ar", languageName: "Arabic" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", language: "fr", languageName: "French" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", language: "sr", languageName: "Serbian" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", language: "fr", languageName: "French" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", language: "en", languageName: "English" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", language: "en", languageName: "English" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", language: "sk", languageName: "Slovak" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", language: "sl", languageName: "Slovenian" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", language: "en", languageName: "English" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", language: "so", languageName: "Somali" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", language: "en", languageName: "English" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", language: "en", languageName: "English" },
  { code: "ES", name: "Spain", flag: "🇪🇸", language: "es", languageName: "Spanish" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", language: "si", languageName: "Sinhala" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", language: "ar", languageName: "Arabic" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", language: "nl", languageName: "Dutch" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", language: "sv", languageName: "Swedish" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", language: "de", languageName: "German" },
  { code: "SY", name: "Syria", flag: "🇸🇾", language: "ar", languageName: "Arabic" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", language: "tg", languageName: "Tajik" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", language: "sw", languageName: "Swahili" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", language: "th", languageName: "Thai" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", language: "pt", languageName: "Portuguese" },
  { code: "TG", name: "Togo", flag: "🇹🇬", language: "fr", languageName: "French" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", language: "en", languageName: "English" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", language: "en", languageName: "English" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", language: "ar", languageName: "Arabic" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", language: "tr", languageName: "Turkish" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", language: "tk", languageName: "Turkmen" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", language: "en", languageName: "English" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", language: "en", languageName: "English" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", language: "uk", languageName: "Ukrainian" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", language: "ar", languageName: "Arabic" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", language: "en", languageName: "English" },
  { code: "US", name: "United States", flag: "🇺🇸", language: "en", languageName: "English" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", language: "es", languageName: "Spanish" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", language: "uz", languageName: "Uzbek" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", language: "bi", languageName: "Bislama" },
  { code: "VA", name: "Vatican City", flag: "🇻🇦", language: "it", languageName: "Italian" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", language: "es", languageName: "Spanish" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", language: "vi", languageName: "Vietnamese" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", language: "ar", languageName: "Arabic" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", language: "en", languageName: "English" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", language: "en", languageName: "English" },
];

// Get country by code
export const getCountryByCode = (code: string): Country | undefined => {
  return allCountries.find(c => c.code === code);
};

// Get language by country code
export const getLanguageByCountry = (code: string): string => {
  const country = allCountries.find(c => c.code === code);
  return country?.language || 'en';
};
